[web]
web-1 ansible_host=172.30.0.11

[proxy]
proxy-1 ansible_host=172.30.0.12

[monitoring]
monitor-1 ansible_host=172.30.0.13

[etcd]
web-1 ansible_host=172.30.0.11
proxy-1 ansible_host=172.30.0.12
monitor-1 ansible_host=172.30.0.13
node-4 ansible_host=172.30.0.14
node-5 ansible_host=172.30.0.15

[daemon]
monitor-1 ansible_host=172.30.0.13

[all:vars]
ansible_user=root
ansible_password=root
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_python_interpreter=/usr/bin/python3